export const WALLET_CONNECT_PROJECT_ID = import.meta.env.VITE_WALLET_CONNECT_PROJECT_ID;

export const FLEEK_FUNCTIONS_ENDPOINT = import.meta.env.VITE_FLEEK_FUNCTIONS_ENDPOINT

export const BICONOMY_BUNDLER_URL = import.meta.env.VITE_BICONOMY_BUNDLER_URL;